### ISSUE TITLE
cuda error with centos7-cuda11 docker images

### ISSUE THREAD

**Issue by eliarcy** [facebookresearch/faiss#1482]
# Summary
I'm trying to compie and run faiss in a CentOS-7 docker image with cuda-11.0, when run the ddemo_ivfpq_indexing_gpu, get a cuda error: 
Faiss assertion 'err__ == cudaSuccess' failed in void faiss::gpu::Tensor<T, Dim, InnerContig, IndexT, PtrTraits>::copyFrom(faiss::gpu::Tensor<T, Dim, InnerContig, IndexT, PtrTraits>&, cudaStream_t) [with T = float; int Dim = 2; bool InnerContig = true; IndexT = int; PtrTraits = faiss::gpu::traits::DefaultPtrTraits; cudaStream_t = CUstream_st*] at ./faiss/gpu/utils/Tensor-inl.cuh:161; details: CUDA error 1 invalid argument

# Platform

CenotOS docker image provided by nvidia

OS: CentOS

Faiss version: 1.6.1

Faiss compilation options: 
1.  ./configure --with-cuda=/usr/local/cuda-11.0/  && make -j for faiss
2. make demo_ivfpq_indexing_gpu for the sample, (int eh gpu/test folder)
3. simply run ./demo_ivfpq_indexing_gpu.

Running on:
- [ ] CPU
- [* ] GPU

Interface: 
- [ *] C++
- [ ] Python

# Reproduction instructions
1. docker pull nvidia/cuda:11.0-devel-centos7 to get the docker images from docker hub
2. nvidia-docker run -it --rm docker-images-id to start a container
3. install openblas, lapack and other libs
4. compile faiss using ./configure --with-cuda=/usr/local/cuda-11.0/  && make -j
5. compile the gpu sample, cd gpu/test && make demo_ivfpq_indexing_gpu
6. run the sample by  ./demo_ivfpq_indexing_gpu.

and gives the error at the begining.

BTW, I use TensorRT-7 in this docker container, it works fine.

**Comment by eliarcy** [comment]
Can Anyone help me on this issue?

**Comment by mdouze** [comment]
no activity, closing.

**Comment by Aurevoir-68** [comment]
> Can Anyone help me on this issue?
@mdouze  @eliarcy     Hello, now the problem has been solved. The reason is that cuda11 has new changes. The specific operations are as follows：
```
gpu/utils/DeviceUtils.cu +114:
else if(att.memoryType == cudaMemoryTypeHost || att.type == 0){
    rerturn -1;
}

````
