### ISSUE TITLE
Select to index on gpu1 but gpu0's memory is also used

### ISSUE THREAD

**Issue by xieyiping** [facebookresearch/faiss#1651]
# Summary
Select to index on gpu1 but gpu0's memory is also used.

# Platform

OS: Ubuntu 16.04.6 LTS 

Faiss version: 1.6.5 

CUDA: 10.1

Installed from: conda install faiss-gpu -c pytorch
 

Running on:
- [ ] CPU
- [x] GPU

Interface: 
- [ ] C++
- [x] Python

# Reproduction instructions

### Code
I use the code from python tutorial [4-GPU.py](https://github.com/facebookresearch/faiss/blob/master/tutorial/python/4-GPU.py) and just change the value of `device` parameter of `index_cpu_to_gpu()` function from `0` to `1` (which means I want use gpu1 to index).
```python
# Copyright (c) Facebook, Inc. and its affiliates.
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.

import numpy as np

d = 64                           # dimension
nb = 100000                      # database size
nq = 10000                       # nb of queries
np.random.seed(1234)             # make reproducible
xb = np.random.random((nb, d)).astype('float32')
xb[:, 0] += np.arange(nb) / 1000.
xq = np.random.random((nq, d)).astype('float32')
xq[:, 0] += np.arange(nq) / 1000.

import faiss                     # make faiss available

res = faiss.StandardGpuResources()  # use a single GPU

## Using a flat index

index_flat = faiss.IndexFlatL2(d)  # build a flat (CPU) index

# make it a flat GPU index
gpu_index_flat = faiss.index_cpu_to_gpu(res, 1, index_flat)

gpu_index_flat.add(xb)         # add vectors to the index
print(gpu_index_flat.ntotal)

loop_num = 10000
for _ in range(loop_num):
    k = 4                          # we want to see 4 nearest neighbors
    D, I = gpu_index_flat.search(xq, k)  # actual search
    # print(I[:5])                   # neighbors of the 5 first queries
    # print(I[-5:])                  # neighbors of the 5 last queries

```

 

### Run results
before run:
```
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  GeForce RTX 208...  Off  | 00000000:40:00.0 Off |                  N/A |
| 27%   21C    P8     1W / 250W |      0MiB / 11019MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  GeForce RTX 208...  Off  | 00000000:41:00.0 Off |                  N/A |
| 27%   21C    P8     2W / 250W |      0MiB / 11019MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
```

during run:
```
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  GeForce RTX 208...  Off  | 00000000:40:00.0 Off |                  N/A |
| 27%   23C    P2    44W / 250W |    190MiB / 11019MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  GeForce RTX 208...  Off  | 00000000:41:00.0 Off |                  N/A |
| 27%   34C    P2   249W / 250W |   1816MiB / 11019MiB |     98%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
```

It takes gpu0's memory, which I don't expect. Because I plan to run the the same numbers of runs on 2 GPUs respectively, but the unexpected gpu memory usage of gpu0 leads to cuda out of memory on gpu0 which stop the runs on gpu1.

Is there anyone knows how to run an index that only uses one gpu's resource(i.e. gpu memory) ?
Thank you.

**Comment by xieyiping** [comment]
I found the problem can be temporally solved by adding the flowing code.
```python
import os
devs = "1"  # use gpu1 not gpu0
os.environ["CUDA_DEVICE_ORDER"] = "PCI_BUS_ID"
os.environ["CUDA_VISIBLE_DEVICES"] = devs
```
