### ISSUE TITLE
Does faiss support CUDA9?

### ISSUE THREAD

**Issue by ShT3ch** [facebookresearch/faiss#273]
Hello.

I built CPU version based on openBLAS, ran cpu-test, it was successful, then I tried to build GPU version. 
It compiles, but test gives me an error: 
```
> test/demo_ivfpq_indexing_gpu
[3.922 s] Generating 100000 vectors in 128D for training
[4.141 s] Training the index
Training IVF quantizer on 100000 vectors in 128D
Clustering 100000 points in 128D to 1788 clusters, redo 1 times, 10 iterations
  Preprocessing in 0.77 s
Faiss assertion 'err__ == cudaSuccess' failed in void faiss::gpu::runL2Norm(faiss::gpu::Tensor<T, 2, true, TIndex>&, faiss::gpu::Tensor<T, 1, true, TIndex>&, bool, cudaStream_t) [with T = float; TVec = float4; TIndex = int; cudaStream_t = CUstream_st*] at impl/L2Norm.cu:239; details: CUDA error 48
Aborted
```

I used CUDA9 as the latest available SDK. I have Titan X card, so I can use 6.1 computational pack(even on 6.0 gpu-test fails).

Trere is gpu part of makefile:

The important part I changed
```
CUDAROOT=/usr/local/cuda-9.0/
...
-gencode arch=compute_61,code="compute_61" \
```

Full listing
```
# a C++ compiler that supports c++11
CC11=g++

# root of the cuda 8 installation
CUDAROOT=/usr/local/cuda-9.0/

CUDACFLAGS=-I$(CUDAROOT)/include

NVCC=$(CUDAROOT)/bin/nvcc

NVCCFLAGS= $(CUDAFLAGS) \
   -I $(CUDAROOT)/targets/x86_64-linux/include/ \
   -Xcompiler -fPIC \
   -Xcudafe --diag_suppress=unrecognized_attribute \
   -gencode arch=compute_61,code="compute_61" \
   --std c++11 -lineinfo \
   -ccbin $(CC11) -DFAISS_USE_FLOAT16

# BLAS LD flags for nvcc (used to generate an executable)
# if BLASLDFLAGS contains several flags, each one may
# need to be prepended with -Xlinker
BLASLDFLAGSNVCC=-Xlinker $(BLASLDFLAGS)

# Same, but to generate a .so
BLASLDFLAGSSONVCC=-Xlinker  $(BLASLDFLAGS)
```

In `nvidia-smi` I see it loads proximately 2.5 Gb of zero gpu device(I have multiple) memory.

**Comment by ShT3ch** [comment]
I rebuilt gpu version with change

`-gencode arch=compute_61,code="compute_61"`
`   |`
`   v`
```
-gencode arch=compute_35,code="compute_35"\
-gencode arch=compute_52,code="compute_52"\
-gencode arch=compute_60,code="compute_60"\
-gencode arch=compute_61,code="compute_61" \
```

And now everything works.

**Comment by duchengyao** [comment]
I build with cuda9 but error

```
impl/../utils/MathOperators.cuh(289): error: class "__half" has no member "x"
```
