### ISSUE TITLE
Difficulty Compiling GPU version on AWS libcublas

### ISSUE THREAD

**Issue by drydenb** [facebookresearch/faiss#886]
# Summary

I am facing an issue running `./configure` in preparation for installing the GPU version of Faiss. The image that I am using is a standard image on AWS named `tensorflow-training:1.13-horovod-gpu-py36-cu100-ubuntu16.04`.

I suspect that this issue may be encountered by other individuals using Faiss on AWS default images and thus I believe this issue is helpful to discuss here. Any feedback is much appreciated.

# Platform

The Docker image used is: `tensorflow-training:1.13-horovod-gpu-py36-cu100-ubuntu16.04` on AWS, described here: https://docs.aws.amazon.com/dlami/latest/devguide/deep-learning-containers-images.html. Installation of cuda is in `/usr/local/cuda`.

CUDA version details:
```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2018 NVIDIA Corporation
Built on Sat_Aug_25_21:08:01_CDT_2018
Cuda compilation tools, release 10.0, V10.0.130
```

Faiss version: git commit: 656368b5eda4d376177a3355673d217fa95000b6

Faiss compilation options: 
```
CPPFLAGS="-I/usr/local/cuda/include" LDFLAGS="-L/usr/local/cuda/lib64"
```

Running on:
- [ ] CPU
- [X] GPU

Interface: 
- [ ] C++
- [X] Python

# Reproduction instructions

After running the following command:
```
CPPFLAGS="-I/usr/local/cuda/include" LDFLAGS="-L/usr/local/cuda/lib64" ./configure
```
Configuration fails with:
```
checking for g++... g++
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking whether g++ supports C++11 features with -std=c++11... yes
checking for gcc... gcc
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking how to run the C preprocessor... gcc -E
checking whether make sets $(MAKE)... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for python... python
checking for Python C flags... -I/usr/local/include/python3.6m -I/usr/local/include/python3.6m
checking for numpy headers path... /usr/local/lib/python3.6/site-packages/numpy/core/include
checking for swig... swig
checking how to run the C++ preprocessor... g++ -std=c++11 -E
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for nvcc... nvcc
checking cuda.h usability... yes
checking cuda.h presence... yes
checking for cuda.h... yes
checking for cublasAlloc in -lcublas... no
configure: error: in `/var/notebooks/common/github/facebookresearch/faiss':
configure: error: Couldn't find libcublas
See `config.log' for more details
```
Checking `/usr/local/cuda/lib64`, it seems that `libcublas` exists with `cublasAlloc`:
```
lrwxrwxrwx 1 root root        21 Sep 12  2018 libcublas.so.10.0 -> libcublas.so.10.0.130
-rw-r--r-- 1 root root  70796360 Sep 12  2018 libcublas.so.10.0.130
```
and
```
nm -D libcublas.so.10.0 | grep cublasAlloc
000000000013a450 T cublasAlloc
```
At this point I am stumped as to what the issue is.

Any ideas or suggestions are greatly appreciated, thanks!

**UPDATE**

I was able to get a bit further with this issue by creating a symlink `libcublas.so -> libcublas.so.10.0.130` within `/usr/local/cuda/lib64` that allowed configure to run, but the new issue is that `gpu/GpuResources.h` is including `cublas_v2.h` but the header is not included in the CUDA 10 installation for this AWS image:
```
In file included from gpu/StandardGpuResources.h:11:0,
                 from gpu/StandardGpuResources.cpp:9:
gpu/GpuResources.h:13:23: fatal error: cublas_v2.h: No such file or directory
compilation terminated.
Makefile:40: recipe for target 'gpu/StandardGpuResources.o' failed
make: *** [gpu/StandardGpuResources.o] Error 1
make: *** Waiting for unfinished jobs....
```
(`find / -name cublas_v2.h` produces no result)

**Comment by drydenb** [comment]
I was able to resolve this issue, and I found the reason somewhat surprising. The installation that is default for CUDA on the image `tensorflow-training:1.13-horovod-gpu-py36-cu100-ubuntu16.04` simply differs from the one that you can download from NVIDIA directly (even matching the version). Thus, the header files etc. are not found and the compilation fails.

For all those who have this problem in the future please check the integrity of your CUDA installation.

Closing this issue as it is now resolved.

**Comment by zaemyung** [comment]
@drydenb So how did you resolve the issue? Did you re-install CUDA?
